name: Docker Image CI


on:
  workflow_run:
    workflows: ["Java CI with Maven"]   # Name must match the first workflow's `name`
    types:
      - completed

jobs:

  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-war
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
